In [1]:
import numpy as np

In [2]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
a=np.array([[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]])
a[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [4]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr=arr.astype(float)
arr

array([10., 20., 30., 40., 50.])

In [5]:
import numpy as np  
A = np.array([[1, 2, 3],  
              [4, 5, 6],  
              [7, 8, 9]])  
B = A.T  
print(B[1, 2])

8


In [6]:
votes=np.array([775,887,676,667,445])
cost=np.array(["878.0","455.0","878.0","445.0","345.0"])



In [7]:
a=["hello",23]
np.array(a)

array(['hello', '23'], dtype='<U21')

In [8]:
[1,2,3,4]*5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
votes*2

array([1550, 1774, 1352, 1334,  890])

In [10]:
# Array dimension and shape

In [11]:
o=np.array([1,2,3,4])
o.shape

(4,)

In [12]:
o.ndim

1

In [13]:
m=np.array([[1,2,3,4],[4,5,6,7]])
m

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [14]:
m.shape

(2, 4)

In [15]:
m.ndim

2

In [16]:
a=np.array(['1.1','2.3'])


In [17]:
a=a.astype(float)
a

array([1.1, 2.3])

In [18]:
a=a.astype(str)
a

array(['1.1', '2.3'], dtype='<U32')

In [19]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[12,13,14,15]]])
a.ndim

3

In [20]:
w=np.array([10,3,4,21,32,76])
type(w)

numpy.ndarray

In [21]:
w[0]

np.int64(10)

In [22]:
w[-1]

np.int64(76)

In [23]:
w[::-1]

array([76, 32, 21,  4,  3, 10])

In [24]:
w[-1:-7:-1]

array([76, 32, 21,  4,  3, 10])

In [25]:
w[len(w)-1]

np.int64(76)

In [26]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [27]:
a=np.arange(1,10,1.1)
a

array([1. , 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [28]:
a[3:6]

array([4.3, 5.4, 6.5])

In [29]:
a[::]

array([1. , 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [30]:
a[6::-1]

array([7.6, 6.5, 5.4, 4.3, 3.2, 2.1, 1. ])

In [31]:
a[-1:-7:-1]

array([9.8, 8.7, 7.6, 6.5, 5.4, 4.3])

In [32]:
arr = np.arange(10)
arr[::-3]


array([9, 6, 3, 0])

In [33]:
##Fancy Indexing

In [34]:
a[a>3.5]

array([4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [35]:
a[(a>3) & (a<9.2)]

array([3.2, 4.3, 5.4, 6.5, 7.6, 8.7])

In [36]:
# Take a sample of 50 restaurants
sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])

In [37]:
restaurants_data = np.column_stack((sample_votes, sample_costs))

In [38]:
restaurants_data[0]

array([775., 800.])

In [39]:
u=np.arange(10,100,10).reshape(3,3)
u

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
u[2][1]

np.int64(80)

In [41]:
u[0][0]

np.int64(10)

In [42]:
p=u.T
p

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [43]:
sum(p)

array([ 60, 150, 240])

In [44]:
s=np.sum(p,1)
s

array([120, 150, 180])

In [45]:
restaurants_data[5:26, :]

array([[ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.],
       [ 150.,  600.],
       [ 164.,  500.],
       [ 424.,  450.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  93.,  300.],
       [  62.,  400.],
       [ 180.,  500.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 506.,  500.],
       [ 172.,  750.],
       [ 415.,  500.]])

In [46]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
np.sum(arr,1)

array([10, 26, 42])

In [48]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr1[0:5]

array([1, 2, 3, 4, 5])

In [50]:
arr1[-1:-6:-1]

array([10,  9,  8,  7,  6])

In [51]:
np.concatenate((arr1[0:5], arr1[-1:-6:-1]))

array([ 1,  2,  3,  4,  5, 10,  9,  8,  7,  6])

In [52]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [53]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [54]:
a=np.arange(22,71,2)
a

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [55]:
np.arange(21, 72, 2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [56]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a[::-1].T

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [58]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [59]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [60]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [61]:
import numpy as np
a = np.array([91, 12, 73, 44, 98, 35, 67, 89])
idx = np.argpartition(a,3)[-3:]
print(a[idx])

[89 91 98]


In [62]:
import numpy as np

In [69]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
x[4:7]

array([5, 6, 7])

In [71]:
x[[2,6,0]]

array([3, 7, 1])

In [75]:
x[x<6]

array([1, 2, 3, 4, 5])

In [76]:
g=np.array([1,3,42,5,21,65])
g

array([ 1,  3, 42,  5, 21, 65])

In [77]:
np.where(g>40,"YES","NO")

array(['NO', 'NO', 'YES', 'NO', 'NO', 'YES'], dtype='<U3')

In [86]:
a=np.arange(1,51).reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [90]:
np.where(a>24,"Yes","No")

array([['No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes']], dtype='<U3')

In [93]:
A=np.arange(1,21).reshape(4,5)
B=np.arange(10,30).reshape(4,5)

In [94]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [95]:
B

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [96]:
np.where(A>12,A,B)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [100]:
np.any(A<19)

np.True_

In [102]:
np.all(A>=1)

np.True_

In [107]:
a=np.random.randint(4,27,size=(4,6))
a

array([[24,  9,  7, 23, 19, 10],
       [18, 15, 13, 14, 20, 20],
       [25, 10,  6, 22, 18, 19],
       [21, 13, 14, 24, 10, 20]], dtype=int32)

In [108]:
np.any(a>6,axis=0)

array([ True,  True,  True,  True,  True,  True])

In [109]:
np.any(a>6,axis=1)

array([ True,  True,  True,  True])

In [116]:
np.all(a>12,axis=1)

array([False,  True, False, False])

In [115]:
np.any((a>6)  | (a<43))

np.True_

In [117]:
a

array([[24,  9,  7, 23, 19, 10],
       [18, 15, 13, 14, 20, 20],
       [25, 10,  6, 22, 18, 19],
       [21, 13, 14, 24, 10, 20]], dtype=int32)

In [118]:
np.sort(a,axis=1)

array([[ 7,  9, 10, 19, 23, 24],
       [13, 14, 15, 18, 20, 20],
       [ 6, 10, 18, 19, 22, 25],
       [10, 13, 14, 20, 21, 24]], dtype=int32)

In [120]:
np.sort(a,axis=0)

array([[18,  9,  6, 14, 10, 10],
       [21, 10,  7, 22, 18, 19],
       [24, 13, 13, 23, 19, 20],
       [25, 15, 14, 24, 20, 20]], dtype=int32)

In [121]:
np.sort(a,axis=0)[::,::-1]

array([[10, 10, 14,  6,  9, 18],
       [19, 18, 22,  7, 10, 21],
       [20, 19, 23, 13, 13, 24],
       [20, 20, 24, 14, 15, 25]], dtype=int32)

In [122]:
b=np.random.randint(1,37,size=(6,6))
b

array([[ 2,  8, 29, 14,  1, 30],
       [28, 32, 18, 12,  5, 35],
       [12, 27, 20, 24,  6,  6],
       [ 4, 29, 30, 18, 19,  3],
       [14, 15, 26, 14, 26, 20],
       [11,  6,  8, 31, 21, 26]], dtype=int32)

In [123]:
c=a@b
c

array([[ 852, 1681, 2262, 1602, 1252, 1786],
       [1168, 1801, 2152, 1896, 1377, 2105],
       [ 951, 1704, 2305, 1851, 1396, 2056],
       [1030, 1928, 2263, 1978, 1306, 1961]], dtype=int32)

In [124]:
np.matmul(a,b)

array([[ 852, 1681, 2262, 1602, 1252, 1786],
       [1168, 1801, 2152, 1896, 1377, 2105],
       [ 951, 1704, 2305, 1851, 1396, 2056],
       [1030, 1928, 2263, 1978, 1306, 1961]], dtype=int32)

In [125]:
np.dot(a,b)

array([[ 852, 1681, 2262, 1602, 1252, 1786],
       [1168, 1801, 2152, 1896, 1377, 2105],
       [ 951, 1704, 2305, 1851, 1396, 2056],
       [1030, 1928, 2263, 1978, 1306, 1961]], dtype=int32)

In [127]:
x=np.array([1,2,3])
y=np.array([[1],[2],[3]])

In [128]:
x

array([1, 2, 3])

In [129]:
y

array([[1],
       [2],
       [3]])

In [130]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [131]:
r=np.array([[1,2,3],[1,2,3]])
s=np.array([[10],[20]])

In [132]:
r+s

array([[11, 12, 13],
       [21, 22, 23]])

In [133]:
import numpy as np
A = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(A + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
