In [1]:
import numpy as np

In [3]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
a=np.array([[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]])
a[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [7]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr=arr.astype(float)
arr

array([10., 20., 30., 40., 50.])

In [9]:
import numpy as np  
A = np.array([[1, 2, 3],  
              [4, 5, 6],  
              [7, 8, 9]])  
B = A.T  
print(B[1, 2])

8


In [ ]:
votes=np.array([775,887,676,667,445])
cost=np.array(["878.0","455.0","878.0","445.0","345.0"])



In [19]:
a=["hello",23]
np.array(a)

array(['hello', '23'], dtype='<U21')

In [20]:
[1,2,3,4]*5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [21]:
votes*2

array([1550, 1774, 1352, 1334,  890])

In [22]:
# Array dimension and shape

In [23]:
o=np.array([1,2,3,4])
o.shape

(4,)

In [24]:
o.ndim

1

In [25]:
m=np.array([[1,2,3,4],[4,5,6,7]])
m

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [26]:
m.shape

(2, 4)

In [27]:
m.ndim

2

In [28]:
a=np.array(['1.1','2.3'])


In [30]:
a=a.astype(float)
a

array([1.1, 2.3])

In [31]:
a=a.astype(str)
a

array(['1.1', '2.3'], dtype='<U32')