In [2]:
import numpy as np

In [3]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
a=np.array([[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]])
a[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [5]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr=arr.astype(float)
arr

array([10., 20., 30., 40., 50.])

In [6]:
import numpy as np  
A = np.array([[1, 2, 3],  
              [4, 5, 6],  
              [7, 8, 9]])  
B = A.T  
print(B[1, 2])

8


In [7]:
votes=np.array([775,887,676,667,445])
cost=np.array(["878.0","455.0","878.0","445.0","345.0"])



In [8]:
a=["hello",23]
np.array(a)

array(['hello', '23'], dtype='<U21')

In [9]:
[1,2,3,4]*5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [10]:
votes*2

array([1550, 1774, 1352, 1334,  890])

In [11]:
# Array dimension and shape

In [12]:
o=np.array([1,2,3,4])
o.shape

(4,)

In [13]:
o.ndim

1

In [14]:
m=np.array([[1,2,3,4],[4,5,6,7]])
m

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [15]:
m.shape

(2, 4)

In [16]:
m.ndim

2

In [17]:
a=np.array(['1.1','2.3'])


In [18]:
a=a.astype(float)
a

array([1.1, 2.3])

In [19]:
a=a.astype(str)
a

array(['1.1', '2.3'], dtype='<U32')

In [20]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[12,13,14,15]]])
a.ndim

3

In [23]:
w=np.array([10,3,4,21,32,76])
type(w)

numpy.ndarray

In [24]:
w[0]

np.int64(10)

In [26]:
w[-1]

np.int64(76)

In [27]:
w[::-1]

array([76, 32, 21,  4,  3, 10])

In [34]:
w[-1:-7:-1]

array([76, 32, 21,  4,  3, 10])

In [37]:
w[len(w)-1]

np.int64(76)

In [39]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [42]:
a=np.arange(1,10,1.1)
a

array([1. , 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [44]:
a[3:6]

array([4.3, 5.4, 6.5])

In [46]:
a[::]

array([1. , 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [47]:
a[6::-1]

array([7.6, 6.5, 5.4, 4.3, 3.2, 2.1, 1. ])

In [48]:
a[-1:-7:-1]

array([9.8, 8.7, 7.6, 6.5, 5.4, 4.3])