In [1]:
import numpy as np

In [2]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
a=np.array([[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]])
a[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [4]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr=arr.astype(float)
arr

array([10., 20., 30., 40., 50.])

In [5]:
import numpy as np  
A = np.array([[1, 2, 3],  
              [4, 5, 6],  
              [7, 8, 9]])  
B = A.T  
print(B[1, 2])

8


In [6]:
votes=np.array([775,887,676,667,445])
cost=np.array(["878.0","455.0","878.0","445.0","345.0"])



In [7]:
a=["hello",23]
np.array(a)

array(['hello', '23'], dtype='<U21')

In [8]:
[1,2,3,4]*5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
votes*2

array([1550, 1774, 1352, 1334,  890])

In [10]:
# Array dimension and shape

In [11]:
o=np.array([1,2,3,4])
o.shape

(4,)

In [12]:
o.ndim

1

In [13]:
m=np.array([[1,2,3,4],[4,5,6,7]])
m

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [14]:
m.shape

(2, 4)

In [15]:
m.ndim

2

In [16]:
a=np.array(['1.1','2.3'])


In [17]:
a=a.astype(float)
a

array([1.1, 2.3])

In [18]:
a=a.astype(str)
a

array(['1.1', '2.3'], dtype='<U32')

In [19]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[12,13,14,15]]])
a.ndim

3

In [20]:
w=np.array([10,3,4,21,32,76])
type(w)

numpy.ndarray

In [21]:
w[0]

np.int64(10)

In [22]:
w[-1]

np.int64(76)

In [23]:
w[::-1]

array([76, 32, 21,  4,  3, 10])

In [24]:
w[-1:-7:-1]

array([76, 32, 21,  4,  3, 10])

In [25]:
w[len(w)-1]

np.int64(76)

In [26]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [27]:
a=np.arange(1,10,1.1)
a

array([1. , 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [28]:
a[3:6]

array([4.3, 5.4, 6.5])

In [29]:
a[::]

array([1. , 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [30]:
a[6::-1]

array([7.6, 6.5, 5.4, 4.3, 3.2, 2.1, 1. ])

In [31]:
a[-1:-7:-1]

array([9.8, 8.7, 7.6, 6.5, 5.4, 4.3])

In [32]:
arr = np.arange(10)
arr[::-3]


array([9, 6, 3, 0])

In [33]:
##Fancy Indexing

In [34]:
a[a>3.5]

array([4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [35]:
a[(a>3) & (a<9.2)]

array([3.2, 4.3, 5.4, 6.5, 7.6, 8.7])

In [36]:
# Take a sample of 50 restaurants
sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])

In [37]:
restaurants_data = np.column_stack((sample_votes, sample_costs))

In [38]:
restaurants_data[0]

array([775., 800.])

In [39]:
u=np.arange(10,100,10).reshape(3,3)
u

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
u[2][1]

np.int64(80)

In [41]:
u[0][0]

np.int64(10)

In [42]:
p=u.T
p

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [43]:
sum(p)

array([ 60, 150, 240])

In [44]:
s=np.sum(p,1)
s

array([120, 150, 180])

In [45]:
restaurants_data[5:26, :]

array([[ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.],
       [ 150.,  600.],
       [ 164.,  500.],
       [ 424.,  450.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  93.,  300.],
       [  62.,  400.],
       [ 180.,  500.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 506.,  500.],
       [ 172.,  750.],
       [ 415.,  500.]])

In [46]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
np.sum(arr,1)

array([10, 26, 42])

In [48]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr1[0:5]

array([1, 2, 3, 4, 5])

In [50]:
arr1[-1:-6:-1]

array([10,  9,  8,  7,  6])

In [51]:
np.concatenate((arr1[0:5], arr1[-1:-6:-1]))

array([ 1,  2,  3,  4,  5, 10,  9,  8,  7,  6])

In [52]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [53]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [54]:
a=np.arange(22,71,2)
a

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [55]:
np.arange(21, 72, 2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [56]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a[::-1].T

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [58]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [59]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [60]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [61]:
import numpy as np
a = np.array([91, 12, 73, 44, 98, 35, 67, 89])
idx = np.argpartition(a,3)[-3:]
print(a[idx])

[89 91 98]


In [62]:
import numpy as np

In [63]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
x[4:7]

array([5, 6, 7])

In [65]:
x[[2,6,0]]

array([3, 7, 1])

In [66]:
x[x<6]

array([1, 2, 3, 4, 5])

In [67]:
g=np.array([1,3,42,5,21,65])
g

array([ 1,  3, 42,  5, 21, 65])

In [68]:
np.where(g>40,"YES","NO")

array(['NO', 'NO', 'YES', 'NO', 'NO', 'YES'], dtype='<U3')

In [69]:
a=np.arange(1,51).reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [70]:
np.where(a>24,"Yes","No")

array([['No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes']], dtype='<U3')

In [71]:
A=np.arange(1,21).reshape(4,5)
B=np.arange(10,30).reshape(4,5)

In [72]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
B

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [74]:
np.where(A>12,A,B)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [75]:
np.any(A<19)

np.True_

In [76]:
np.all(A>=1)

np.True_

In [77]:
a=np.random.randint(4,27,size=(4,6))
a

array([[ 4, 13,  7, 22,  7, 21],
       [ 4, 18, 18, 25, 26, 25],
       [22, 26, 10, 16,  6, 17],
       [13, 17, 11, 20, 20, 13]], dtype=int32)

In [78]:
np.any(a>6,axis=0)

array([ True,  True,  True,  True,  True,  True])

In [79]:
np.any(a>6,axis=1)

array([ True,  True,  True,  True])

In [80]:
np.all(a>12,axis=1)

array([False, False, False, False])

In [81]:
np.any((a>6)  | (a<43))

np.True_

In [82]:
a

array([[ 4, 13,  7, 22,  7, 21],
       [ 4, 18, 18, 25, 26, 25],
       [22, 26, 10, 16,  6, 17],
       [13, 17, 11, 20, 20, 13]], dtype=int32)

In [83]:
np.sort(a,axis=1)

array([[ 4,  7,  7, 13, 21, 22],
       [ 4, 18, 18, 25, 25, 26],
       [ 6, 10, 16, 17, 22, 26],
       [11, 13, 13, 17, 20, 20]], dtype=int32)

In [84]:
np.sort(a,axis=0)

array([[ 4, 13,  7, 16,  6, 13],
       [ 4, 17, 10, 20,  7, 17],
       [13, 18, 11, 22, 20, 21],
       [22, 26, 18, 25, 26, 25]], dtype=int32)

In [85]:
np.sort(a,axis=0)[::,::-1]

array([[13,  6, 16,  7, 13,  4],
       [17,  7, 20, 10, 17,  4],
       [21, 20, 22, 11, 18, 13],
       [25, 26, 25, 18, 26, 22]], dtype=int32)

In [86]:
b=np.random.randint(1,37,size=(6,6))
b

array([[17, 21, 28, 15,  9,  9],
       [30, 23, 17,  7, 18, 26],
       [10,  5, 33, 22,  2,  2],
       [28, 16, 11,  7, 23, 14],
       [13, 13,  2, 18, 28, 29],
       [ 5,  4, 12, 23, 28, 35]], dtype=int32)

In [87]:
c=a@b
c

array([[1340,  945, 1072, 1068, 1574, 1634],
       [1951, 1426, 1639, 1800, 2399, 2519],
       [1865, 1512, 1780, 1343, 1698, 1887],
       [1726, 1351, 1432, 1355, 1829, 1896]], dtype=int32)

In [88]:
np.matmul(a,b)

array([[1340,  945, 1072, 1068, 1574, 1634],
       [1951, 1426, 1639, 1800, 2399, 2519],
       [1865, 1512, 1780, 1343, 1698, 1887],
       [1726, 1351, 1432, 1355, 1829, 1896]], dtype=int32)

In [89]:
np.dot(a,b)

array([[1340,  945, 1072, 1068, 1574, 1634],
       [1951, 1426, 1639, 1800, 2399, 2519],
       [1865, 1512, 1780, 1343, 1698, 1887],
       [1726, 1351, 1432, 1355, 1829, 1896]], dtype=int32)

In [90]:
x=np.array([1,2,3])
y=np.array([[1],[2],[3]])

In [91]:
x

array([1, 2, 3])

In [92]:
y

array([[1],
       [2],
       [3]])

In [93]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [94]:
r=np.array([[1,2,3],[1,2,3]])
s=np.array([[10],[20]])

In [95]:
r+s

array([[11, 12, 13],
       [21, 22, 23]])

In [96]:
import numpy as np
A = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(A + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [97]:
import numpy as np
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)






[False  True False  True]


In [98]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [99]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [100]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [101]:
def cal(n):
    if n %2==0:
        return n+2
    else:
        return n*2

In [102]:
cal(344445)

688890

In [103]:
l=[1,2,3,4,5]


In [104]:
a

array([100, 200, 300, 400])

In [105]:
cal_vec=np.vectorize(cal)

In [106]:
cal_vec(arr)

array([[ 4,  6,  6, 10],
       [ 2, 14,  6, 10],
       [ 4, 10,  8, 18],
       [22, 46, 14, 38]])

In [107]:
b=np.random.randint(1,37,size=(6,6))
b

array([[30, 10, 17, 20, 13, 32],
       [ 5, 18, 19,  5,  1, 21],
       [13, 16, 29, 36,  4, 22],
       [36, 14, 36, 26,  2, 31],
       [13,  1, 36, 11,  8,  5],
       [34, 35, 35, 34, 23, 10]], dtype=int32)

In [108]:
cal_vec(b)

array([[32, 12, 34, 22, 26, 34],
       [10, 20, 38, 10,  2, 42],
       [26, 18, 58, 38,  6, 24],
       [38, 16, 38, 28,  4, 62],
       [26,  2, 38, 22, 10, 10],
       [36, 70, 70, 36, 46, 12]], dtype=int32)

In [109]:
arr=np.array([1,2,3,4,5,6])
sp=np.split(arr,3)
sp

[array([1, 2]), array([3, 4]), array([5, 6])]

In [110]:
new=np.split(b,3,axis=0)
new

[array([[30, 10, 17, 20, 13, 32],
        [ 5, 18, 19,  5,  1, 21]], dtype=int32),
 array([[13, 16, 29, 36,  4, 22],
        [36, 14, 36, 26,  2, 31]], dtype=int32),
 array([[13,  1, 36, 11,  8,  5],
        [34, 35, 35, 34, 23, 10]], dtype=int32)]

In [111]:
new=np.hsplit(b,3)
new

[array([[30, 10],
        [ 5, 18],
        [13, 16],
        [36, 14],
        [13,  1],
        [34, 35]], dtype=int32),
 array([[17, 20],
        [19,  5],
        [29, 36],
        [36, 26],
        [36, 11],
        [35, 34]], dtype=int32),
 array([[13, 32],
        [ 1, 21],
        [ 4, 22],
        [ 2, 31],
        [ 8,  5],
        [23, 10]], dtype=int32)]

In [112]:
new=np.vsplit(b,3)
new

[array([[30, 10, 17, 20, 13, 32],
        [ 5, 18, 19,  5,  1, 21]], dtype=int32),
 array([[13, 16, 29, 36,  4, 22],
        [36, 14, 36, 26,  2, 31]], dtype=int32),
 array([[13,  1, 36, 11,  8,  5],
        [34, 35, 35, 34, 23, 10]], dtype=int32)]

In [113]:
new=np.array_split(b,2,axis=0)
new

[array([[30, 10, 17, 20, 13, 32],
        [ 5, 18, 19,  5,  1, 21],
        [13, 16, 29, 36,  4, 22]], dtype=int32),
 array([[36, 14, 36, 26,  2, 31],
        [13,  1, 36, 11,  8,  5],
        [34, 35, 35, 34, 23, 10]], dtype=int32)]

In [114]:
w=np.arange(1,16).reshape(5,3)
w

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [115]:
np.array_split(w,[1,2],axis=0)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])]

In [116]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(np.hsplit(arr, 2))

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [117]:
a1=np.array([[1],[2],[3]])
a2=np.array([[5],[3],[4]])
v=np.vstack([a1,a2])
v

array([[1],
       [2],
       [3],
       [5],
       [3],
       [4]])

In [118]:
v=np.hstack([a1,a2])
v

array([[1, 5],
       [2, 3],
       [3, 4]])

In [119]:
v.ndim

2

In [120]:
import numpy as np
a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]]


In [123]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [126]:
np.full(shape=(3,5),fill_value="HEY")

array([['HEY', 'HEY', 'HEY', 'HEY', 'HEY'],
       ['HEY', 'HEY', 'HEY', 'HEY', 'HEY'],
       ['HEY', 'HEY', 'HEY', 'HEY', 'HEY']], dtype='<U3')

In [127]:
np.arange(1,5,1)

array([1, 2, 3, 4])

In [132]:
np.random.randint(1,10,[5,5])

array([[5, 7, 2, 2, 2],
       [3, 4, 4, 3, 5],
       [9, 4, 5, 7, 1],
       [6, 3, 2, 2, 9],
       [5, 5, 6, 7, 3]], dtype=int32)

In [149]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [151]:
a[::-1]

array([5, 4, 3, 2, 1])

In [152]:
b=np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [155]:
b[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [156]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(np.hstack((arr, arr[:, [0]])).shape)

(3, 4)


In [2]:
import pandas as pd

In [7]:
df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})
df

,emp_id,name,dept
0,1,Ram,IT
1,2,Shyam,Ops


In [8]:
import pandas as pd 
df = pd.DataFrame({'A': [10, 20, 30], 
                  'B': [40, 50, 60]}, 
                  index=['x', 'y', 'z']) 
print(df.loc['x':'y'])
print(df.iloc[0:2])

    A   B
x  10  40
y  20  50
    A   B
x  10  40
y  20  50
